#import "AppDelegate.h"
#import <KudanAR/ARAPIKey.h>

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{    
    [[ARAPIKey sharedInstance] setAPIKey:@"nGzWRBFSI2Ep+i2dMjAhycae3e8ZX54NwPQDLihmRqg9GWbZnWkZSfQ3Oz9NXn6YDA1QP4w6TyfqKsxu1ZoYo0mrTWcNd7+LI5RyEwvryqjQ2fqiMxW599SleTZNl3FICFfHMk/ANxmkumEgakx5KxpOjGFJPToyVzpne9ugs4YPmnrJsNipIibS15Ef4E2zoSfY1ELAKoCCHvoc36tayRys0nzHbeJrwix/KPDRR7KhxvTz5i7iWCvbcYjLj/MRTcB2JSUaKDpK0F4oVm2s6oLJamHZcBEJX+YyhWPn0yevricarmORtaXGWOkX6ouqogI88twd9cZbZ8ELvigEwgXgl5eXmQ4oZGIep22I0eXF+rmxjt+dCTmYn+GeXGD3falEbh9ab8f8wZL6yZelDpzwUfhg+brnE0VB3ZFoONOgo4BvoBq1O+9IF+Hk7i76wcc6B2bBUaEfz4SwNh6+EwZfTJf5PgerObWHhXCMXiBKQ60jHTAZIWVe9oRiC0Lf9At457KSmhayhCcbs+rcW4A1I1X5ceXeJv91nfrmbWNsfVMpcTfxKEg4LZuIaVrPNdNSfVWGAKXFMFC4h8SdPdNaMcngDodP2Fkw8yQzA8mw6nOd8BzQqhDsyaoPId30N3dD3tBNBUk9F4LafAVRhlVBiZhoYgYwcbAs7JmsWNo="];
    
    return YES;
}

@end
